repos:
-   repo: local
    hooks:
    -   id: terraform_format
        name: terraform_format
        entry: --entrypoint /src/hooks/terraform_format.sh hashicorp/terraform:1.5.2
        language: docker_image
-   repo: local
    hooks:
    -   id: terraform_validate
        name: terraform_validate
        entry: "--entrypoint /src/hooks/terraform_validate.sh -v tfvalidate:/src/cache hashicorp/terraform:1.5.2"
        language: docker_image
-   repo: local
    hooks:
    -   id: tflint
        name: tflint
        entry: --entrypoint /src/hooks/tflint.sh ghcr.io/terraform-linters/tflint:v0.48.0
        language: docker_image
-   repo: local
    hooks:
    -   id: tfsec
        name: tfsec
        entry: --entrypoint /src/hooks/tfsec.sh aquasec/tfsec:v1.28
        language: docker_image
-   repo: local
    hooks:
    -   id: terraform_docs
        name: terraform_docs
        entry: --entrypoint /src/hooks/terraform_docs.sh quay.io/terraform-docs/terraform-docs:0.16.0
        language: docker_image
